services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_GROQ_API_KEY=${REACT_APP_GROQ_API_KEY}
